### ISSUE TITLE
Disable classification propagation when uploading entities

### ISSUE THREAD

**Issue by fBedecarrats** [wjohnson/pyapacheatlas#71] opened 2021-01-27 09:08 UTC
Currently, pyapacheatlas uploads entity classifications with the propagation attribute activated.
This is not convenient for all use cases. For instance, one would like to add a classification such as "manual_import" to differentiate, when browsing the catalog, the entities imported with pyapacheatlas from those populated automatically. Currently, when uploading related entities with this classification, one ends up with a series of "propagated classifications" stating "manual_import manual_import manual_import manual_import..." as many times as there are relationthips (which can be >10 in my case).

**Comment by wjohnson** [comment] 2021-01-27 13:02
@fBedecarrats would you be able to share the excel template you were using?  Or at least a few sample rows?

**Comment by fBedecarrats** [comment] 2021-01-27 15:29
Hello and thanks for the quick feedback! The specifics of the data I'm using is a bit cryptic and somewhat confidential/sensitive, so I created a generic content with something simpler: [Example_lineage_01.xlsx](https://github.com/wjohnson/pyapacheatlas/files/5881159/Example_lineage_01.xlsx)

The uploading script is the following:
```python
# %% Create a custom classification

custom_classification = {
"classificationDefs":[
    {
     "category": "CLASSIFICATION",
     "name": "manual_import",
     "description": "Not generated with an automated import process",
     "typeVersion": "1.0",
     "attributeDefs": [],
     "superTypes": []
     }
    ]
}

test = client.upload_typedefs(custom_classification)

# %% Parse excel file

ec = ExcelConfiguration()
reader = ExcelReader(ec)
file_path = "./Example_lineage_01.xlsx"
entities = reader.parse_bulk_entities(filepath = file_path)
typedefs = reader.parse_entity_defs(file_path)
lineage_processes = reader.parse_update_lineage(file_path)

# %% Load types and entities from Excel

type_results = client.upload_typedefs(typedefs, force_update=False)
entity_results = client.upload_entities(entities)
results = client.upload_entities(lineage_processes)
```

If you check the the result in the catalog UI, you will see that the entity with "Waiting_time_displays" as qualified name has one attributed  "manual_import" classification and 4 propagated "manual_import" classifications. It would be useful to disable classification propagation in such a case, to keep only the attributed classification.
Best regards

**Comment by wjohnson** [comment] 2021-01-27 17:18
@fBedecarrats Thank you for sharing that excel and code to reproduce the scenario.

Have you parsed and uploaded the contents of your excel multiple times?  I saw that repeated classifications issue in the Purview UI a few weeks ago but that might be getting resolved.  I ran through the code and I only see the one manual_import.  I might be on a slightly further ahead version 🤫 

![image](https://user-images.githubusercontent.com/1058199/106027443-8356e800-6090-11eb-89b8-c81c4e4528b2.png)

In addition, at this time, Purview does not support classification propagation 😞 so what you're seeing has to be a bug in the UI / processing in Purview.

**Comment by fBedecarrats** [comment] 2021-01-27 18:18
I am sorry not to have specified this earlier: I am running my tests with a local instance of Apache Atlas 2.1, and not with Purview. Basically, what I do is `docker run -d -p 21000:21000 --name atlas sburn/apache-atlas /opt/apache-atlas-2.1.0/bin/atlas_start.py`, which fetches [this docker image](https://github.com/sburn/docker-apache-atlas), then:
```
from pyapacheatlas.auth import BasicAuthentication
from pyapacheatlas.core import AtlasClient
from pyapacheatlas.readers import ExcelConfiguration, ExcelReader
# Default credentials for testing image
auth = BasicAuthentication(username = "admin", password = "admin")
client = AtlasClient(endpoint_url = "http://localhost:21000/api/atlas/v2",
    authentication = auth)
```
Then the code copied above.
What I get is the following result in Apache Atlas UI (the duplicated propagated classifications are framed in the red box):
![apache_classification_propagation](https://user-images.githubusercontent.com/3328347/106035275-36950080-60d4-11eb-8a6e-5abce16dee79.png)
I understand that this behaviour might be specific to Apache Atlas and not applicable to Purview, so it might not require a resolution if the scope of pyapacheatlas is specifically focused on Purview.

**Comment by wjohnson** [comment] 2021-01-28 22:00
@fBedecarrats Thank you so much for sharing that this was apache atlas!  I 100% want to support Apache Atlas as much as possible but it does take a back seat to Azure Purview. However, this will certainly be a bug when Purview implements this.

In the context of Apache Atlas, I think the right DEFAULT is to block propagation, right?
http://atlas.apache.org/api/v2/json_AtlasClassification.html

I think if the more advanced users want to use propagation, they can either modify the Python package OR they can modify the output themselves (since parse_bulk_entities returns the entities dict).

If the default classification being added to the entity BLOCKED propagation, would that solve this issue?

**Comment by wjohnson** [comment] 2021-01-29 01:04
@fBedecarrats can you try the [fix in this branch](https://github.com/wjohnson/pyapacheatlas/tree/fix/excelClassificationProp)?

**Comment by fBedecarrats** [comment] 2021-01-29 09:36
Thanks for this quick feedback! I created a new environment and installed the fix branch with `pip install git+https://github.com/wjohnson/pyapacheatlas.git@fix/excelClassificationProp`, then created a clean Atlas instance with `docker run -d -p 21000:21000 --name atlas2 sburn/apache-atlas /opt/apache-atlas-2.1.0/bin/atlas_start.py`, then relaunched the following script, that use the same Excel template than provided above:
```
# %% Load dependencies

from pyapacheatlas.auth import BasicAuthentication
from pyapacheatlas.core import AtlasClient
from pyapacheatlas.readers import ExcelConfiguration, ExcelReader

# %% Set connection to Atlas

# The default credentials when testing Atlas locally
auth = BasicAuthentication(
    username = "admin", 
    password = "admin"
)

# The default location when testing locally
client = AtlasClient(
    endpoint_url = "http://localhost:21000/api/atlas/v2",
    authentication = auth
)

# Get all existing type definitions
all_type_defs = client.get_all_typedefs()

# %% Create a custom classification

custom_classification = {
"classificationDefs":[
    {
     "category": "CLASSIFICATION",
     "name": "manual_import",
     "description": "Ne provient pas d'un import automatisé",
     "typeVersion": "1.0",
     "attributeDefs": [],
     "superTypes": []
     }
    ]
}

test = client.upload_typedefs(custom_classification)

# %% Parse excel file

ec = ExcelConfiguration()
reader = ExcelReader(ec)
file_path = "./Example_lineage_01.xlsx"
entities = reader.parse_bulk_entities(filepath = file_path)
typedefs = reader.parse_entity_defs(file_path)
lineage_processes = reader.parse_update_lineage(file_path)

# %% Load types and entities from Excel

type_results = client.upload_typedefs(typedefs, force_update=False)
entity_results = client.upload_entities(entities)
results = client.upload_entities(lineage_processes)
``` 
And the resutls in Apache Atlas is the following :
![apache_classification_propagation_solved](https://user-images.githubusercontent.com/3328347/106257842-613ea080-621d-11eb-8cc5-4bb8cf3ca0d3.png)
As you can see, the propagated classification tags do not appear anymore, which clearly solves the issue.
Many thanks and congratulations!

**Comment by wjohnson** [comment] 2021-01-29 13:55
@fBedecarrats Thank you for your patience and willingness to work through this with me. These changes will be included in the next release to pypi!

I really appreciate you trying the package out and using it with Apache Atlas! I'll be hacking away at your other suggestions soon as well!

**Closed** 2021-01-29 14:46 UTC
Labels: bug
